# Generated by Django 5.1.1 on 2024-11-10 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_event_organizer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_time',
        ),
    ]
