# Generated by Django 5.1.1 on 2024-09-30 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='comment_id',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='event_id',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='post_id',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='reminder_time',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='role',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='update_type',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='video_id',
        ),
        migrations.AlterField(
            model_name='notifications',
            name='notification_type',
            field=models.CharField(choices=[('comment_post', 'Comment on Post'), ('comment_video', 'Comment on Video'), ('reply_comment', 'Reply to Comment'), ('like_post', 'Like on Post'), ('like_comment', 'Like on Comment')], max_length=50),
        ),
    ]
