# Generated by Django 5.1.1 on 2024-11-08 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_notification_course_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('comment_post', 'Comment on Post'), ('reply_comment', 'Reply to Comment'), ('like_post', 'Like on Post'), ('like_comment', 'Like on Comment'), ('new_course', 'New Course Available'), ('course_update', 'Course Updated')], max_length=50),
        ),
    ]
