# Generated by Django 5.1.1 on 2024-11-14 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='event_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('comment_post', 'Comment on Post'), ('reply_comment', 'Reply to Comment'), ('like_post', 'Like on Post'), ('like_comment', 'Like on Comment'), ('event_created', 'New Event Created'), ('event_updated', 'Event Updated'), ('new_course', 'New Course Available'), ('course_update', 'Course Updated')], max_length=50),
        ),
    ]
